name: dingding_webhook
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Await CF Pages and send Slack notification
        id: cf-pages
        uses: buyfakett/cloudflare-pages-dingding-webhook@v6.2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACC_ID  }}
          project: ${{ secrets.CF_PAGES_PROJECT  }}
          dingWebHookKey: ${{ secrets.DING_WEBHOOK_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}